### ISSUE TITLE
most properties like content_type, file_size should be optional

### ISSUE THREAD

**Issue by gucki** [krobertson/dm-paperclip#7]
Just as the original gem allows us, it should be possible to have the properties content_type, file_size, updated_at to be optional. 

'm now sure what the best way to do this. May be by passing an option like :custom_properties => true to has_attached_file and then it's up to the model to define all properties?

**Comment by krobertson** [comment]
I'll take a look at this.  It would likely be the opposite though.  You'd have to opt-in to disabling the fields.  If by default, it no longer utilized those fields, then that'd be a big deviation and breaking change for existing users and existing apps.  Since the number of people who don't want to use them is smaller, would need to specify to disable them.
